### ISSUE TITLE
Tests & Docs

### ISSUE THREAD

**Issue by jonwinton** [clay/amphora#389]
# Tasks
- [x] Get Amphora back to 100% code coverage
- [ ] Write docs for Amphora
- [ ] Remove `TODO` comments
- [ ] Document the delete, save, render hooks

## Document
- [ ] Plugins
- [ ] Renderers

**Comment by jonwinton** [comment]
Integrated Gitbooks into repo for docs in https://github.com/clay/amphora/pull/444

Publishes to http://clay.github.io/amphora/

Lots to document still
