### ISSUE TITLE
Amphora v7.x

### ISSUE THREAD

**Issue by jonwinton** [clay/amphora#551]
# Goals
- [ ] Destructure DB interactions to use use plug-and-play modules for reading/writing to any DB/Cache
- [ ] Deprecate plugins API in favor of Event Bus
- [ ] Strict enforcement of publishing layouts
- [ ] Remove Eventify from DB service
- [ ] Bus can be plugged in
